### ISSUE TITLE
[BUG] Unable to stream Telemetry Events

### ISSUE THREAD

**Issue by themegaphoenix** [Azure/azure-iot-explorer#477]
**Describe the bug**
Events are not being streamed and shown in the Telemetry tab. Works fine on 0.14.5

**To Reproduce**
1. Clone https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/samples/pnp
2. Start it up and send telemetry events
3. Go to the Devices and then Telemetry and start streaming 

**Expected behavior**
Events show up

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version 10 
 - App version 0.14.6

**Additional context**
Works fine on 0.14.5

**Comment by YingXue** [comment]
Hi @themegaphoenix 
Thank you very much for reporting the issue! We will release a new version to address the issue. Meanwhile, please fall back to the old version. Sorry for the inconvinience.

**Comment by YingXue** [comment]
Fixed in release 0.14.7

**Comment by smanni-et** [comment]
> Fixed in release 0.14.7

@YingXue the bug is still there in 0.14.7 as reported also in #481 

Rollback to 0.14.5 or previous is the only way to have the telemetry stream working.
